# Generated by Django 3.2.5 on 2021-08-01 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import profit_calculator.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('type', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('running_cost', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='running cost (£/seat/100km)')),
                ('range', models.PositiveSmallIntegerField(verbose_name='range (km)')),
                ('max_standard_class', models.PositiveSmallIntegerField(help_text='Max number of seats if all of them are standard class.')),
                ('min_first_class', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AircraftPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_first_class', models.PositiveSmallIntegerField(null=True, verbose_name='Number of first class seats')),
                ('num_standard_class', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Number of standard class seats')),
                ('aircraft', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profit_calculator.aircraft')),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('distance_from_lpl', models.PositiveSmallIntegerField()),
                ('distance_from_boh', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AirportPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uk_airport', models.CharField(choices=[('LPL', 'Liverpool John Lennon Airport'), ('BOH', 'Bournemouth International Airport')], default='', max_length=3, verbose_name='UK airport')),
                ('distance', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='distance between airports (km)')),
                ('foreign_airport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profit_calculator.airport')),
            ],
        ),
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_class_price', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('first_class_price', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('cost_per_seat', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Running cost per seat')),
                ('running_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total running cost')),
                ('income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('profit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlightPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('save_name', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('aircraft_plan', models.OneToOneField(auto_created=True, blank=True, default=profit_calculator.models.default_aircraftplan, on_delete=django.db.models.deletion.SET_DEFAULT, to='profit_calculator.aircraftplan')),
                ('airport_plan', models.OneToOneField(auto_created=True, blank=True, default=profit_calculator.models.default_airportplan, on_delete=django.db.models.deletion.SET_DEFAULT, to='profit_calculator.airportplan')),
                ('pricing_plan', models.OneToOneField(auto_created=True, blank=True, default=profit_calculator.models.default_pricingplan, on_delete=django.db.models.deletion.SET_DEFAULT, to='profit_calculator.pricingplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
