# Generated by Django 3.2.5 on 2021-07-23 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profit_calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightplan',
            name='save_name',
            field=models.CharField(max_length=100),
        ),
    ]
