# Generated by Django 3.2.5 on 2021-07-27 11:12

from django.db import migrations, models
import django.db.models.deletion
import profit_calculator.models


class Migration(migrations.Migration):

    dependencies = [
        ('profit_calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraftplan',
            name='num_standard_class',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Number of standard class seats'),
        ),
        migrations.AlterField(
            model_name='airportplan',
            name='distance',
            field=models.FloatField(blank=True, null=True, verbose_name='distance between airports'),
        ),
        migrations.AlterField(
            model_name='flightplan',
            name='aircraft_plan',
            field=models.OneToOneField(blank=True, default=profit_calculator.models.AircraftPlan, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='profit_calculator.aircraftplan'),
        ),
        migrations.AlterField(
            model_name='flightplan',
            name='airport_plan',
            field=models.OneToOneField(blank=True, default=profit_calculator.models.AirportPlan, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='profit_calculator.airportplan'),
        ),
        migrations.AlterField(
            model_name='flightplan',
            name='pricing_plan',
            field=models.OneToOneField(blank=True, default=profit_calculator.models.PricingPlan, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='profit_calculator.pricingplan'),
        ),
    ]
