# Generated by Django 3.2.5 on 2021-07-20 10:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profit_calculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightplan',
            name='save_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='flightplan',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created/last updated'),
        ),
    ]
