# Generated by Django 3.2.5 on 2021-07-27 11:25

from django.db import migrations, models
import django.db.models.deletion
import profit_calculator.models


class Migration(migrations.Migration):

    dependencies = [
        ('profit_calculator', '0002_auto_20210727_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightplan',
            name='aircraft_plan',
            field=models.OneToOneField(auto_created=True, blank=True, default=profit_calculator.models.AircraftPlan, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='profit_calculator.aircraftplan'),
        ),
        migrations.AlterField(
            model_name='flightplan',
            name='airport_plan',
            field=models.OneToOneField(auto_created=True, blank=True, default=profit_calculator.models.AirportPlan, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='profit_calculator.airportplan'),
        ),
        migrations.AlterField(
            model_name='flightplan',
            name='pricing_plan',
            field=models.OneToOneField(auto_created=True, blank=True, default=profit_calculator.models.PricingPlan, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='profit_calculator.pricingplan'),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='cost_per_seat',
            field=models.FloatField(blank=True, null=True, verbose_name='Running cost per seat'),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='income',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='profit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='running_cost',
            field=models.FloatField(blank=True, null=True, verbose_name='Total running cost'),
        ),
    ]
