# Generated by Django 3.2.5 on 2021-07-27 11:36

from django.db import migrations, models
import django.db.models.deletion
import profit_calculator.models


class Migration(migrations.Migration):

    dependencies = [
        ('profit_calculator', '0003_auto_20210727_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightplan',
            name='aircraft_plan',
            field=models.OneToOneField(auto_created=True, blank=True, default=profit_calculator.models.default_aircraftplan, on_delete=django.db.models.deletion.SET_DEFAULT, to='profit_calculator.aircraftplan'),
        ),
        migrations.AlterField(
            model_name='flightplan',
            name='airport_plan',
            field=models.OneToOneField(auto_created=True, blank=True, default=profit_calculator.models.default_airportplan, on_delete=django.db.models.deletion.SET_DEFAULT, to='profit_calculator.airportplan'),
        ),
        migrations.AlterField(
            model_name='flightplan',
            name='pricing_plan',
            field=models.OneToOneField(auto_created=True, blank=True, default=profit_calculator.models.default_pricingplan, on_delete=django.db.models.deletion.SET_DEFAULT, to='profit_calculator.pricingplan'),
        ),
    ]
