# Generated by Django 3.2.5 on 2021-07-30 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profit_calculator', '0004_auto_20210727_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='range',
            field=models.PositiveSmallIntegerField(verbose_name='range (km)'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='distance_from_boh',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='airport',
            name='distance_from_lpl',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='airportplan',
            name='distance',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='distance between airports'),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='cost_per_seat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Running cost per seat'),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='running_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total running cost'),
        ),
    ]
