# Generated by Django 3.2.5 on 2021-07-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profit_calculator', '0005_auto_20210730_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airportplan',
            name='distance',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='distance between airports (km)'),
        ),
    ]
