# Generated by Django 3.2.5 on 2021-08-01 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profit_calculator', '0006_alter_airportplan_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraftplan',
            name='aircraft',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profit_calculator.aircraft'),
        ),
        migrations.AlterField(
            model_name='airportplan',
            name='foreign_airport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profit_calculator.airport'),
        ),
    ]
